ollama run qwen2.5-coder:14b "Please alter the colors and theme of this existing CSS stylesheet to a new theme of a Artistic Splash Palette: Bold primary colors like red, blue, and yellow, mixed with splashes of black and white, creating a dynamic and creative expression. Ensure light and dark mode via prefers-color-scheme is still supported. Do not change anything except for the colors. BEGIN EXISTING CSS: $(cat mini-theme-original.css)" >> mini-theme-artsy.css

ollama run qwen2.5-coder:14b "Please alter the colors and theme of this existing CSS stylesheet to a new theme of a Candy Shop Palette: Bright and playful colors like bubblegum pink, lemon yellow, and mint green, reminiscent of sweet treats and fun experiences. Ensure light and dark mode via prefers-color-scheme is still supported. Do not change anything except for the colors. BEGIN EXISTING CSS: $(cat mini-theme-original.css)" >> mini-theme-candy.css

ollama run qwen2.5-coder:14b "Please alter the colors and theme of this existing CSS stylesheet to a new theme of a Coffee Palette: Rich espresso brown, creamy latte beige, warm caramel, soft mocha, and a hint of deep forest green for accents. Ensure light and dark mode via prefers-color-scheme is still supported. Do not change anything except for the colors. BEGIN EXISTING CSS: $(cat mini-theme-original.css)" >> mini-theme-coffee.css

ollama run qwen2.5-coder:14b "Please alter the colors and theme of this existing CSS stylesheet to a new theme of a Festival Fun Palette: Bright fuchsia, electric blue, and sunny yellow, capturing the lively spirit of music festivals and celebrations. Ensure light and dark mode via prefers-color-scheme is still supported. Do not change anything except for the colors. BEGIN EXISTING CSS: $(cat mini-theme-original.css)" >> mini-theme-festival.css

ollama run qwen2.5-coder:14b "Please alter the colors and theme of this existing CSS stylesheet to a new theme of a Minimalist Monochrome Palette: Shades of gray, black, and white, offering a sleek and modern look that emphasizes simplicity and elegance. Ensure light and dark mode via prefers-color-scheme is still supported. Do not change anything except for the colors. BEGIN EXISTING CSS: $(cat mini-theme-original.css)" >> mini-theme-monochrome.css

ollama run qwen2.5-coder:14b "Please alter the colors and theme of this existing CSS stylesheet to a new theme of a Rustic Charm Palette: Earthy browns and deep greens paired with warm beige and soft terracotta, evoking a cozy cabin feel surrounded by nature. Ensure light and dark mode via prefers-color-scheme is still supported. Do not change anything except for the colors. BEGIN EXISTING CSS: $(cat mini-theme-original.css)" >> mini-theme-rustic.css

ollama run qwen2.5-coder:14b "Please alter the colors and theme of this existing CSS stylesheet to a new theme of a Sunset Glow Palette: Warm oranges, deep purples, and soft pinks, reflecting the beautiful hues of a sunset for a romantic and dreamy feel. Ensure light and dark mode via prefers-color-scheme is still supported. Do not change anything except for the colors. BEGIN EXISTING CSS: $(cat mini-theme-original.css)" >> mini-theme-sunset.css

ollama run qwen2.5-coder:14b "Please alter the colors and theme of this existing CSS stylesheet to a new theme of a Tropical Paradise Palette: Vibrant greens, hot pinks, and sunny oranges, reminiscent of exotic fruits and lush landscapes, creating a lively and cheerful atmosphere. Ensure light and dark mode via prefers-color-scheme is still supported. Do not change anything except for the colors. BEGIN EXISTING CSS: $(cat mini-theme-original.css)" >> mini-theme-tropical.css
